=pod

=encoding utf8

=head1 NAME

Muldis::D::Core -
Muldis D core data types and operators

=head1 VERSION

This document is Muldis::D::Core version 0.75.0.

=head1 PREFACE

This document is part of the Muldis D language specification, whose root
document is L<Muldis::D>; you should read that root document
before you read this one, which provides subservient details.

That said, because this C<Core> document is otherwise too large to
comfortably fit in one file, it has been split into pieces and therefore
has its own tree of parts to follow, which it is the root of:
L<Muldis::D::Core::Types>, L<Muldis::D::Core::Types_Catalog>,
L<Muldis::D::Core::Routines>, L<Muldis::D::Core::Routines_Catalog>.

=head1 DESCRIPTION

Muldis D has a mandatory core set of system-defined (eternally available)
entities, which is referred to as the I<Muldis D core> or the I<core>; they
are the minimal entities that all Muldis D implementations need to provide;
they are mutually self-describing and are used to bootstrap the language;
any entities outside the core, called I<Muldis D extensions>, are
non-mandatory and are defined in terms of the core or each other, but the
reverse isn't true.

This current C<Core> document features the boolean type and operators, plus
the integer, bit string, and character string types, plus the q/tuple and
q/relation type constructors and the more important
relational operators, plus the type system minimal and maximal types, plus
the special types used to define the system catalog, and the polymorphic
operators that all types, or some types including core types, have defined
over them, such as identity tests or assignment.  (All of these are used
for bootstrapping the Muldis D language, except for the bit string type,
but that's still good to have in the core.)

Most of the C<Core> document is actually in these pieces:
L<Muldis::D::Core::Types>, L<Muldis::D::Core::Types_Catalog>,
L<Muldis::D::Core::Routines>, L<Muldis::D::Core::Routines_Catalog>.

Extensions are in other documents.

Generic order-concerning types and operators, such as for sorting or quota
queries or plain order-determination, which could be applied to any data
type potentially, are separated into mainly just this extension:
L<Muldis::D::Ext::Ordered>.

All of the generic operators (except those that do or could apply to all
types) concerning the integer numeric, bit string, character string, and
rational numeric types don't exist in C<Core> but have been separated into
language extensions; while they are good for all implementations to have,
they are less necessary than some other operators that actually were kept
in C<Core>.  These are the relevant extensions: L<Muldis::D::Ext::Integer>,
L<Muldis::D::Ext::Blob>, L<Muldis::D::Ext::Text>,
L<Muldis::D::Ext::Rational>.

The most important boolean logic and relational q/nonscalar-concerning
operators exist in C<Core>, but a lot more are available in these
extensions: L<Muldis::D::Ext::Bool>, L<Muldis::D::Ext::QTuple>,
L<Muldis::D::Ext::QRelation>, L<Muldis::D::Ext::QSet>,
L<Muldis::D::Ext::QArray>, L<Muldis::D::Ext::QBag>,
L<Muldis::D::Ext::Counted>.

These extensions do not generally just add operators for core types; rather
they mainly define new types plus just operators for those:
L<Muldis::D::Ext::Temporal>, L<Muldis::D::Ext::Spatial>.

=head1 SEE ALSO

Go to L<Muldis::D> for the majority of distribution-internal
references, and L<Muldis::D::SeeAlso> for the majority of
distribution-external references.

=head1 AUTHOR

Darren Duncan (C<perl@DarrenDuncan.net>)

=head1 LICENSE AND COPYRIGHT

This file is part of the formal specification of the Muldis D language.

Muldis D is Copyright © 2002-2009, Muldis Data Systems, Inc.

See the LICENSE AND COPYRIGHT of L<Muldis::D> for details.

=head1 TRADEMARK POLICY

The TRADEMARK POLICY in L<Muldis::D> applies to this file too.

=head1 ACKNOWLEDGEMENTS

The ACKNOWLEDGEMENTS in L<Muldis::D> apply to this file too.

=cut
