=pod

=encoding utf8

=head1 NAME

Muldis::D::Outdated - Parts of the Muldis D spec yet to be rewritten

=head1 VERSION

This document is Muldis::D::Outdated version 0.201.0.

=head1 DESCRIPTION

See L<Muldis::D> first to read the B<Muldis D> language meta-specification.

This C<Outdated> document provides a catalogue to the remaining
static/archived parts of the C<Muldis_D http://muldis.com 0.148.2>
specification that were not yet replaced by parts of
C<Muldis_D http://muldis.com 0.201.0> specification.

The suggested reading order (but that all follow the root) of C<0.148.2>,
are: L<Muldis::D::Outdated::Basics>, L<Muldis::D::Outdated::Core> (which
has its own tree of parts to follow),
L<Muldis::D::Outdated::Dialect::PTMD_STD>,
L<Muldis::D::Outdated::Dialect::HDMD_Perl6_STD>,
L<Muldis::D::Outdated::Dialect::HDMD_Perl5_STD>,
L<Muldis::D::Outdated::Conventions>, L<Muldis::D::Outdated::Ext::Counted>,
L<Muldis::D::Outdated::Ext::Temporal>, L<Muldis::D::Outdated::Ext::Spatial>.

=head1 SEE ALSO

Go to L<Muldis::D> for the majority of distribution-internal
references, and L<Muldis::D::See_Also> for the majority of
distribution-external references.

=head1 AUTHOR

Darren Duncan (C<darren@DarrenDuncan.net>)

=head1 LICENSE AND COPYRIGHT

This file is part of the formal specification of the Muldis D language.

Muldis D is Copyright © 2002-2018, Muldis Data Systems, Inc.

See the LICENSE AND COPYRIGHT of L<Muldis::D> for details.

=head1 TRADEMARK POLICY

The TRADEMARK POLICY in L<Muldis::D> applies to this file too.

=head1 ACKNOWLEDGEMENTS

The ACKNOWLEDGEMENTS in L<Muldis::D> apply to this file too.

=cut
