=pod

=encoding utf8

=head1 NAME

Muldis::D::Standard_Library - Muldis D common core vocabulary for regular users

=head1 VERSION

This document is Muldis::D::Standard_Library version 0.300.0.

=head1 DESCRIPTION

This document is the human readable authoritative formal specification of
the B<Muldis D Standard Library> (B<MDSL>) primary component of the B<Muldis D>
language.  The fully-qualified name of this document and the specification
it contains is C<Muldis_D_Standard_Library https://muldis.com 0.300.0>.

See also L<Muldis::D> to read the B<Muldis D> language meta-specification.

The B<Muldis D Standard Library> specification comprises a documented
library written entirely in Muldis D which provides its common core
vocabulary, the system-defined data types and operators that regular users
of the language would employ directly in their applications and schemas.
It corresponds to the "standard library" that is intrinsic to or bundled
with typical general purpose application programming languages or SQL
DBMSs.  It is the bulk portion of Muldis D that is self-hosted and can be
shared by all Muldis D implementations, though the latter can choose to
internally substitute behaviour-maintaining host-native versions for
performance.  It comprises a set of Muldis D I<packages> (compilation
units) that users can choose from as dependencies of their applications and
schemas.  None are mandatory, and users can choose alternatives, but they
are recommended as the default options for their functionality.

=head1 PACKAGES

The B<Muldis D Standard Library> comprises these Muldis D packages:

=over

=item *

C<System https://muldis.com 0.300.0> -
L<Muldis::D::Package::System> - Provides the common primary
system-defined data types and operators that regular users of the language
would employ directly in their applications and schemas.

=back

Other packages will be added later, such as C<System::Math>.

=head1 AUTHOR

Darren Duncan (C<darren@DarrenDuncan.net>)

=head1 LICENSE AND COPYRIGHT

This file is part of the formal specification of the B<Muldis D Standard
Library> (B<MDSL>) primary component of the B<Muldis D> language
specification.  MDSL substantially comprises executable code as well.

MDSL is Copyright © 2002-2022, Muldis Data Systems, Inc.

L<https://muldis.com>

MDSL is free software; you can redistribute it and/or
modify it under the terms of the Apache License, Version 2.0 (AL2) as
published by the Apache Software Foundation (L<https://www.apache.org>).
You should have received a copy of the AL2 as part of the MDSL
distribution, in the file named "LICENSE/Apache-2.0.txt";
if not, see L<https://www.apache.org/licenses/LICENSE-2.0>.

Any versions of MDSL that you modify and distribute must carry prominent
notices stating that you changed the files and the date of any changes, in
addition to preserving this original copyright notice and other credits.
MDSL is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.

While it is by no means required, the copyright holder of MDSL would
appreciate being informed any time you create a modified version of MDSL
that you are willing to distribute, because that is a practical way of
suggesting improvements to the standard version.

=cut
