=pod

=encoding utf8

=head1 NAME

Muldis::D::Package::Muldis_D -
Muldis D core data types and operators

=head1 VERSION

This document is Muldis::D::Package::Muldis_D version 0.200.1.

=head1 PREFACE

This document is part of the Muldis D language specification, whose root
document is L<Muldis::D>; you should read that root document
before you read this one, which provides subservient details.

=head1 SYNOPSIS

    Muldis_D:Plain_Text:"http://muldis.com":"0.200.1";
    script ASCII;
    package
    {
        identity My_App ::= My_App:"http://mycorp.com":"0";
        uses
        {
            Muldis_D ::= Muldis_D:"http://muldis.com":"0.200.1";
        };
        materials
        {
            floating {::My_App, ::Muldis_D};

            `TODO: Put example routines etc here.`

        };
    };

=head1 DESCRIPTION

This document defines the Muldis D Plain Text package
C<Muldis_D:"http://muldis.com":"0.200.1"> which provides the common core
system-defined data types and operators that regular users of the language
would employ directly in their applications and schemas.

=head1 PACKAGE

    Muldis_D:Plain_Text:"http://muldis.com":"0.200.1";
    script ASCII;
    package
    {
        identity Muldis_D ::= Muldis_D:"http://muldis.com":"0.200.1";
        materials
        {
            floating {::Muldis_D};
            ...
        };
    };

=head1 MAXIMAL AND MINIMAL DATA TYPES

=head2 Anything

    ::Muldis_D::Anything ::= type default false;

    ::Muldis_D::Any ::= synonym of Anything;

The enumeration contract C<Anything> represents the infinite I<universal
type>, which is the maximal data type of the entire Muldis D type system
and consists of all values which can possibly exist.  It also represents
the infinite Muldis D Foundation type I<FDN__Anything>.  Its default value
is C<false>.  Other programming languages may name their corresponding
types I<Any> or I<Object> or I<Universal>.

=head2 Nothing

    ::Muldis_D::Nothing ::= type of {};

The enumeration contract C<Nothing> represents the finite I<empty type>,
which is the minimal data type of the entire Muldis D type system and
consists of exactly zero values.  It can not have any default value.

=head1 GENERIC SIMPLE DATA TYPES

=head2 Boolean

    ::Muldis_D::Boolean ::= type
        where topic -->^ FDN__isa_Boolean
        default false
        composes {Boolish and_provides_its_default,
            Orderable and_provides_its_default};

    ::Muldis_D::Bool ::= synonym of Boolean;

The enumeration contract C<Boolean> represents the finite Muldis D
Foundation type I<FDN__Boolean>.  A C<Boolean> value is a general purpose
2-valued logic boolean, or specifically it is one of the 2 values C<false>
and C<true>.  Its default value is C<false>.

I<TODO.>

Examples:

    true

    false

=head2 Inf_Integer

    ::Muldis_D::Inf_Integer ::= type
        where topic -->^ FDN__isa_Inf_Integer
        default 0 
        composes {Integral and_provides_its_default,
            Cardinal and_provides_its_default, Ordinal};

    ::Muldis_D::Integer ::= synonym of Inf_Integer;
    ::Muldis_D::Int     ::= synonym of Inf_Integer;

The enumeration contract C<Inf_Integer> represents the infinite Muldis D
Foundation type I<FDN__Inf_Integer>.  An C<Inf_Integer> value is a general
purpose integer exact numeric.  Its default value is C<0>.  Other
programming languages may name their corresponding types I<BigInt>.

I<TODO.>

Examples:

    42

    0

    \-3

    \+'-3' '50_897'

    0d39

    0xDEADBEEF

    0o644

    0b11001001

=head2 ...

I<TODO.>

=head1 SEE ALSO

Go to L<Muldis::D> for the majority of distribution-internal
references, and L<Muldis::D::See_Also> for the majority of
distribution-external references.

=head1 AUTHOR

Darren Duncan (C<darren@DarrenDuncan.net>)

=head1 LICENSE AND COPYRIGHT

This file is part of the formal specification of the Muldis D language.

Muldis D is Copyright © 2002-2015, Muldis Data Systems, Inc.

See the LICENSE AND COPYRIGHT of L<Muldis::D> for details.

=head1 TRADEMARK POLICY

The TRADEMARK POLICY in L<Muldis::D> applies to this file too.

=head1 ACKNOWLEDGEMENTS

The ACKNOWLEDGEMENTS in L<Muldis::D> apply to this file too.

=cut
