=pod

=encoding utf8

=head1 NAME

Muldis::D::Outdated::Core::Interval -
Muldis D generic interval operators

=head1 VERSION

This document is Muldis::D::Outdated::Core::Interval version 0.148.2.

=head1 PREFACE

This document is part of the Muldis D language specification, whose root
document is L<Muldis::D>; you should read that root document before
you read this one, which provides subservient details.  Moreover, you
should read the L<Muldis::D::Outdated::Core> document before this current
document, as that forms its own tree beneath a root document branch.

=head1 DESCRIPTION

This document describes essentially all of the core Muldis D generic
interval operators, for the canonical interval types that are tuple or
relation types with specific nonscalar headings.  They can potentially be
used with values of any data type as long as said data type has a (total)
C<order-determination> function defined for it, and all system-defined
conceptually-ordered Muldis D scalar root types do.

I<This documentation is pending.>

I<Most functions that should be in this document are pending.>

Each of these functions is a wrapper over the C<order-determination>
function named C<sys.std.Core.Ordered.order> when the latter function is
primed by a C<misc_args> argument of C<Tuple:D0> and by
an C<is_reverse_order> argument of C<Bool:False>.

These functions' C<SPInterval>-typed arguments' C<min> and C<max> attribute
values must be of compatible declared types with the wrapped functions'
C<topic> and C<other> parameters; otherwise these functions will fail|warn
when the wrapped function would.  Likewise, any other argument values would
be compared to an interval's endpoints must be compatible with them.
Likewise, said attributes of any multiplicity of C<SPInterval>-typed
arguments must be mutually compatible.

=head1 FUNCTIONS IMPLEMENTING VIRTUAL COLLECTIVE FUNCTIONS

=head2 sys.std.Core.Interval.SP.has_member

C<< function has_member (Bool <-- coll : SPInterval, value : Ordered)
implements sys.std.Core.Collective.has_member {...} >>

This function results in C<Bool:True> iff its C<value> argument is included
within the interval defined by its C<coll> argument, and C<Bool:False>
otherwise.  That is, if conceptually the interval represents a set of
values, this function tests if C<value> is a member of C<coll>.

=head2 sys.std.Core.Interval.SP.has_not_member

C<< function has_not_member (Bool <-- coll : SPInterval, value : Ordered)
implements sys.std.Core.Collective.has_not_member {...} >>

This function is exactly the same as C<sys.std.Core.Interval.has_member>
except that it results in the opposite boolean value when given the same
arguments.

=head2 sys.std.Core.Interval.SP.value_is_member

C<< function value_is_member (Bool <-- value : Ordered, coll : SPInterval)
implements sys.std.Core.Collective.value_is_member {...} >>

This function is an alias for C<sys.std.Core.Interval.SP.has_member>.  This
function results in C<Bool:True> iff its C<value> argument is included
within the interval defined by its C<coll> argument, and C<Bool:False>
otherwise.  That is, if conceptually the interval represents a set of
values, this function tests if C<value> is a member of C<coll>.

=head2 sys.std.Core.Interval.SP.value_is_not_member

C<< function value_is_not_member (Bool <--
value : Ordered, coll : SPInterval)
implements sys.std.Core.Collective.value_is_not_member {...} >>

This function is an alias for C<sys.std.Core.Interval.SP.has_not_member>.
This function is exactly the same as
C<sys.std.Core.Interval.SP.value_is_member> except that it
results in the opposite boolean value when given the same arguments.

=head2 sys.std.Core.Interval.MP.has_member

C<< function has_member (Bool <-- coll : MPInterval, value : Ordered)
implements sys.std.Core.Collective.has_member {...} >>

This function results in C<Bool:True> iff its C<value> argument is included
within the interval defined by its C<coll> argument, and C<Bool:False>
otherwise.  That is, if conceptually the interval represents a set of
values, this function tests if C<value> is a member of C<coll>.

=head2 sys.std.Core.Interval.MP.has_not_member

C<< function has_not_member (Bool <-- coll : MPInterval, value : Ordered)
implements sys.std.Core.Collective.has_not_member {...} >>

This function is exactly the same as C<sys.std.Core.Interval.has_member>
except that it results in the opposite boolean value when given the same
arguments.

=head2 sys.std.Core.Interval.MP.value_is_member

C<< function value_is_member (Bool <-- value : Ordered, coll : MPInterval)
implements sys.std.Core.Collective.value_is_member {...} >>

This function is an alias for C<sys.std.Core.Interval.MP.has_member>.  This
function results in C<Bool:True> iff its C<value> argument is included
within the interval defined by its C<coll> argument, and C<Bool:False>
otherwise.  That is, if conceptually the interval represents a set of
values, this function tests if C<value> is a member of C<coll>.

=head2 sys.std.Core.Interval.MP.value_is_not_member

C<< function value_is_not_member (Bool <--
value : Ordered, coll : MPInterval)
implements sys.std.Core.Collective.value_is_not_member {...} >>

This function is an alias for C<sys.std.Core.Interval.MP.has_not_member>.
This function is exactly the same as
C<sys.std.Core.Interval.MP.value_is_member> except that it
results in the opposite boolean value when given the same arguments.

=head1 SEE ALSO

Go to L<Muldis::D> for the majority of distribution-internal
references, and L<Muldis::D::See_Also> for the majority of
distribution-external references.

=head1 AUTHOR

Darren Duncan (C<darren@DarrenDuncan.net>)

=head1 LICENSE AND COPYRIGHT

This file is part of the formal specification of the Muldis D language.

Muldis D is Copyright © 2002-2011, Muldis Data Systems, Inc.

See the LICENSE AND COPYRIGHT of L<Muldis::D> for details.

=head1 TRADEMARK POLICY

The TRADEMARK POLICY in L<Muldis::D> applies to this file too.

=head1 ACKNOWLEDGEMENTS

The ACKNOWLEDGEMENTS in L<Muldis::D> apply to this file too.

=cut
